name: nekonapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_snack_bar: ^0.3.1
  cloud_firestore: ^4.8.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.19.0
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.3
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  lottie: ^2.5.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
