// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIGXY7lbqTEGX6PQoN4UP5uZAXGm83l-g',
    appId: '1:92806545016:web:35ed82aff63b2da4b1f78d',
    messagingSenderId: '92806545016',
    projectId: 'nekonapp',
    authDomain: 'nekonapp.firebaseapp.com',
    storageBucket: 'nekonapp.appspot.com',
    measurementId: 'G-SKQ6C15X0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeQRG_rOT3Bfu63Ey4UK04YC7X4j3AVE',
    appId: '1:92806545016:android:41660b7199aa8f5ab1f78d',
    messagingSenderId: '92806545016',
    projectId: 'nekonapp',
    storageBucket: 'nekonapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0yXjYfGmEu0pIr2T8wDFfw3UR0PaYiI',
    appId: '1:92806545016:ios:aec23931046639ffb1f78d',
    messagingSenderId: '92806545016',
    projectId: 'nekonapp',
    storageBucket: 'nekonapp.appspot.com',
    iosClientId: '92806545016-0bnvl3ccsam9ktm51dhggbv9q8g7haq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nekonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0yXjYfGmEu0pIr2T8wDFfw3UR0PaYiI',
    appId: '1:92806545016:ios:b790b89a743c3fd0b1f78d',
    messagingSenderId: '92806545016',
    projectId: 'nekonapp',
    storageBucket: 'nekonapp.appspot.com',
    iosClientId: '92806545016-ffdlrh0dq641vv0jdnfkgai1pij9lf92.apps.googleusercontent.com',
    iosBundleId: 'com.example.nekonapp.RunnerTests',
  );
}
